name: calc_wood
description: "Wood Business Suite"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  go_router: ^16.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.20.2
  uuid: ^4.5.1
  url_launcher: ^6.3.2
  share_plus: ^11.1.0
  path_provider: ^2.1.5
  pdf: ^3.11.3
  printing: ^5.14.2
  image_picker: ^1.2.0
  google_nav_bar: ^5.0.7
  collection: ^1.19.1
  animated_icon_button: ^1.0.2
  lottie: ^3.3.1
  flutter_native_splash: ^2.4.6
  flutter_screenutil: ^5.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.11
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animation/

  fonts:
    - family: Cairo-Black
      fonts:
        - asset: assets/fonts/Cairo-Black.ttf
    - family: Cairo-Bold
      fonts:
        - asset: assets/fonts/Cairo-Bold.ttf
    - family: Cairo-ExtraBold
      fonts:
        - asset: assets/fonts/Cairo-ExtraBold.ttf
    - family: Cairo-ExtraLight
      fonts:
        - asset: assets/fonts/Cairo-ExtraLight.ttf
    - family: Cairo-Light
      fonts:
        - asset: assets/fonts/Cairo-Light.ttf
    - family: Cairo-Medium
      fonts:
        - asset: assets/fonts/Cairo-Medium.ttf
    - family: Cairo-Regular
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
    - family: Cairo-SemiBold
      fonts:
        - asset: assets/fonts/Cairo-SemiBold.ttf

flutter_native_splash:
  color: "0xFF305700"                  # لون الخلفية
  image: assets/images/logopic.png     # لوجو التطبيق
  android_gravity: center
  ios_content_mode: center
  web_image_mode: center

  android_12:
    image: assets/images/logopic.png
    color: "#305700"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/cubelogo.png"   # أيقونة التطبيق
  adaptive_icon_background: "#305700"        # خلفية الأيقونة (لو اندرويد 8+)
  adaptive_icon_foreground: "assets/images/cubelogo.png"